## Default server configuration
---
server:
  applicationConnectors:
    - type: http
      port: 8080

defaultGenre: Unknown
defaultRating: Unrated

database:
  driverClass: org.h2.Driver
  url: "jdbc:h2:mem:"
  user: sa
  password: sa

